/** Auto-generated by scripts/optimize-images.mjs — do not edit */
export const imageManifest = {
  "beach": {
    "base": "beach",
    "width": 1600,
    "height": 1200,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "camogli": {
    "base": "camogli",
    "width": 1920,
    "height": 1440,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "compare": {
    "base": "compare",
    "width": 1600,
    "height": 1200,
    "fallbackWidth": 1600,
    "fallbackHeight": 1200,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cruise-port": {
    "base": "cruise-port",
    "width": 1920,
    "height": 1440,
    "fallbackWidth": 1920,
    "fallbackHeight": 1440,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "family": {
    "base": "family",
    "width": 1920,
    "height": 582,
    "fallbackWidth": 800,
    "fallbackHeight": 242,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "ferry": {
    "base": "ferry",
    "width": 1500,
    "height": 1000,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food": {
    "base": "food",
    "width": 1920,
    "height": 1280,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero-home": {
    "base": "hero-home",
    "width": 1600,
    "height": 1200,
    "fallbackWidth": 1600,
    "fallbackHeight": 1200,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "og-default": {
    "base": "og-default",
    "width": 1600,
    "height": 1200,
    "fallbackWidth": 1600,
    "fallbackHeight": 1200,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ],
    "og": {
      "width": 1200,
      "height": 630
    },
    "ogSrc": "/images/opt/og-default-og1200.jpg"
  },
  "photography": {
    "base": "photography",
    "width": 1920,
    "height": 1440,
    "fallbackWidth": 1920,
    "fallbackHeight": 1440,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "portofino": {
    "base": "portofino",
    "width": 1600,
    "height": 1200,
    "fallbackWidth": 1600,
    "fallbackHeight": 1200,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "riviera-coast": {
    "base": "riviera-coast",
    "width": 1600,
    "height": 1200,
    "fallbackWidth": 1600,
    "fallbackHeight": 1200,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "train": {
    "base": "train",
    "width": 1920,
    "height": 1450,
    "fallbackWidth": 800,
    "fallbackHeight": 604,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  }
} as const;

export type ImageManifestEntry = (typeof imageManifest)[keyof typeof imageManifest];
